trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build

  - stage: Test
    jobs:
      - job: Test
        steps:
            displayName: 'Run tests'

  - stage: Security
    jobs:
      - job: Security
        steps:
          - script: |
              source venv/bin/activate
              pip install bandit
              bandit -r .
            displayName: 'Run security scans'

  - stage: Deploy
    jobs:
      - deployment: Deploy
        environment: 'staging'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: Kubernetes@1
                  inputs:
                    connectionType: 'Azure Resource Manager'
                    azureSubscription: 'Service Connection'
                    azureResourceGroup: 'example-resources'
                    kubernetesCluster: 'example-aks-cluster'
                    namespace: 'default'
                    command: 'apply'
                    useConfigurationFile: true
                    configuration: '$(System.DefaultWorkingDirectory)/manifests/*.yaml'

